"""Add detailed defect log fields

Revision ID: 1f78737bb7e8
Revises: 4deea2363b6d
Create Date: 2026-01-04 13:03:54.581008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f78737bb7e8'
down_revision = '4deea2363b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_resolution_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('responsible_department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('defect_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('verification_result', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('verification_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rework_operator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qc_operator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'employees', ['rework_operator_id'], ['id'])
        batch_op.create_foreign_key(None, 'employees', ['qc_operator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('qc_operator_id')
        batch_op.drop_column('rework_operator_id')
        batch_op.drop_column('verification_notes')
        batch_op.drop_column('verification_result')
        batch_op.drop_column('defect_status')
        batch_op.drop_column('responsible_department')
        batch_op.drop_column('target_resolution_date')

    # ### end Alembic commands ###
