"""Add ProductionWorkerLog and simplify statuses

Revision ID: 2b38e9c2747a
Revises: 
Create Date: 2026-01-02 04:12:15.396153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b38e9c2747a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qc_inspector_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'employees', ['qc_inspector_id'], ['id'])

    with op.batch_alter_table('production_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_supervisor_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('production_tasks_pic_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['line_supervisor_id'], ['id'])
        batch_op.drop_column('pic_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('production_tasks_pic_id_fkey'), 'employees', ['pic_id'], ['id'])
        batch_op.drop_column('line_supervisor_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('qc_inspector_id')

    # ### end Alembic commands ###
