"""Add dso_status to orders

Revision ID: 4deea2363b6d
Revises: 2b38e9c2747a
Create Date: 2026-01-03 15:01:20.278360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4deea2363b6d'
down_revision = '2b38e9c2747a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dso_status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('qc_sheet', schema=None) as batch_op:
        batch_op.alter_column('production_task_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc_sheet', schema=None) as batch_op:
        batch_op.alter_column('production_task_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('dso_status')

    # ### end Alembic commands ###
